Fix misaligned lines in debugger
software-mansion/radon-ide pull request #634
Opened 2024-10-16 20:11 UTC by filip131311

This PR fixes a problem with debugger on expo projects, caused by prelude lines added to the entry bundle file added by expo. The solution uses `__EXPO_ENV_PRELUDE_LINES__` as a source of information about the required offset. Because offset is only required for the initial bundle as only this one contains additional lines from expo, we add it to the first source map and then set it to 0. 

It is possible that the changes will no longer be needed in future versions of react native as the expo team tries to correct source map generation to include extra lines, for more information read those PRs:
- [expo side ](https://github.com/expo/expo/pull/29463)
- [metro side](https://github.com/facebook/metro/pull/1284)
This is why we add version check before adding lineOffset to initial source map.

### How Has This Been Tested: 
- open expo project and set a breakpoint, before the changes it would trigger 2 lines above the place it's been set. 
- save any change in the file containing breakpoint and make sure it still works.
- check if links to files generated next to console logs are pointing in to the correct place, again both before and after making changes to the file.
- check if error position indicator (when uncaught exception  is raised) points to the correct position. 

### Additional changes: 
This PR also fixes a minor mistake with `getReactNativeVersion` utility that does not need to be async and as it is used, we make it synchronous as part of this PR.

2024-10-16 22:09 UTC, kmagiera requested changes
I don't like the coupling between console calls that are also meant to provide the offset and the source map parser that seems to expect the console call prior to the "source maps ready" call.

I think we should instead restructure it in the following way:
1. Remove `__EXPO_ENV_PRELUDE_LINES__` entirely
2. Instead of it, we should log a command from metro process that will be captured by line reader. Similarily to how we do with RNIDE_initialize_done, but it will also contain the offset number
3. Read the offset in metro.ts using line reader and expose it such that we can provide it as a parameter to the debug session

2024-10-16 22:09 UTC, kmagiera commented on packages/vscode-extension/src/debugging/DebugAdapter.ts
> +              shouldApplyOffset ? this.lineOffset : 0,
this seems to assume that we will get some console log call before source maps are provided such that this.lineOffect can be set.

2024-10-17 10:21 UTC, filip131311 commented
@kmagiera  you were right, I changed it according to your suggestions.

2024-10-17 11:31 UTC, kmagiera requested changes

2024-10-17 11:31 UTC, kmagiera commented on packages/vscode-extension/lib/metro_helpers.js
> +      process.stdout.write(JSON.stringify({ type: "RNIDE_Expo_Env_Prelude_Lines", expoEnvPreludeLines }));
For consistency with RNIDE_initialize_done I wouldn't use capitalized words here

2024-10-17 11:31 UTC, kmagiera commented on packages/vscode-extension/src/project/metro.ts
> +  private _initialBundleLineOffset = 0;
I don't like "initial" word here as it isn't accurate. I think the offset applies for the whole bundle not just for the first bundle that gets loaded as it is currently implemented.

We should rename "mainBundleLineOffset"

2024-10-17 11:31 UTC, kmagiera commented on packages/vscode-extension/src/debugging/DebugAdapter.ts
> +            const shouldApplyOffset =
This check isn't accurate I think, we don't want to use the offset for the first source map only but for any source map that covers the prelude bit. Meaning that all JS reloads would also have this issue, while we may not handle them correctly. Have you tried using reloadJS with your changes now? Note that when we calculate generated position, we do a full loop over all the maps and if the entry is found in multiple maps, we take the last record. So the newer source map will be considered in that case.

2024-10-17 15:33 UTC, kmagiera commented
I'm now thinking that it may actually be the easiest solution to still include the offset in the bundle, and when we get source map we'd check if the offset variable exists there and read its value. If this would work, that'd be the best solution in my option. The only reason why it may not work is that I'm not sure if the preamble actually gets included in the source map at all. Tthe reason we're adding this offset was that there was an issue with that. But, perhaps, the issue was only because it is considered to have 0 length rather than just being completely omitted. You'll need to check the bundle for that to tell

2024-10-21 22:39 UTC, kmagiera approved these changes
Left a few more comments inline, but since only related to variable/parameter names and comments I'm accepting, as otherwise the code looks good.
The only comment that may require more attention is about whether we should test agains expo or react native version when determining when to use offset parameter and when not

2024-10-21 22:39 UTC, kmagiera commented on packages/vscode-extension/src/debugging/DebugAdapter.ts
> +            const isFileWithOffset = sourceMap.sources.includes("__prelude__");
rename `isMainBundle` or `isFullBundle`

2024-10-21 22:39 UTC, kmagiera commented on packages/vscode-extension/src/debugging/DebugAdapter.ts
> +            // module that is added by expo, but not reported in the source map
```suggestion
            // We detect when a source map for the entire bundle is loaded by checking
            // if __env__ module is present in the sources.
```

2024-10-21 22:39 UTC, kmagiera commented on packages/vscode-extension/src/debugging/DebugAdapter.ts
> +    this.lineOffset = configuration.lineOffset;
This parameter should really be called `expoPreludeExtraLines` or something along these lines instead of being so generic

2024-10-21 22:39 UTC, kmagiera commented on packages/vscode-extension/src/debugging/DebugAdapter.ts
> +              semver.lte(getReactNativeVersion(), "0.76.0") && isFileWithOffset;
should we check for expo version here and not react native?

2024-10-21 22:39 UTC, kmagiera commented on packages/vscode-extension/src/debugging/DebugAdapter.ts
> +            // in upcoming versions and if the changes are still not added bump the version below.
```suggestion
            // When using expo <${PUT_VERSION_HERE}, source maps skip the prelude module which is 
            // included in the main bundle at the start. As a result, all lines in the main bundle are shifted by
            // the amount of lines the prelude file adds. To offset this, we use the lineOffset parameter that we pass
            // to the source maps list that is used later on to correct line numbers when translating from generated
            // to the original positions.
```

2024-10-22 09:51 UTC, merged