Add Open Deep Link modal
software-mansion/radon-ide pull request #640
Opened 2024-10-21 08:09 UTC by km1chno

Resolves #631 

## Changes

Adds "Open Deep Link" modal that allows to input a deep link to open in app and browse history of recently opened deep links, which is cached in workspace state.

## Demos (dark and light mode)

https://github.com/user-attachments/assets/5f98a1bd-7a51-4261-bc05-52d5b019c3b9

https://github.com/user-attachments/assets/f66f9a67-9d89-4060-afd0-19f34ea3faf8

### How Has This Been Tested: 

Tested in light and dark mode, on Iphone 15 Pro sim and Pixel 9 emulator, on projects `expo-router` and `react-native-75`.

2024-10-21 22:02 UTC, kmagiera requested changes
While I haven't reviewed the code yet, wanted to add some UX related comments based on the videos you attached:
1) It doesn't feel good when the height of the dialog changes when you type (there are less choices as you narrow down the search, but shifting the modal makes it difficult to type or follow).
2) I think it'd make sense for this to work similarily to the browser URL bar, specifically it doesn't seem like we really need to input fields for the URL and for search separately. The main one should be a typeahead (using past history) input

2024-10-28 11:39 UTC, kmagiera commented
From the UX perspective it makes little sense to have the magnifier glass icon there. It is an input field that also narrows down the history list.

I'd perhaps just leave it without any icon and instead add placeholder "Enter deeplink or search history"

I'd also experiment with adding some label for the list of previous entries such that it is clear what we show there. For example "History" or "Previously used URLs"

2024-10-30 10:36 UTC, km1chno commented
@kmagiera what do you think about something like this?

<img width="620" alt="Zrzut ekranu 2024-10-30 o 11 36 32" src="https://github.com/user-attachments/assets/1a01e9e9-06f5-41fe-bcca-b96878aa2796">

2024-10-30 10:40 UTC, kmagiera commented
Looks good!

2024-10-30 13:44 UTC, kmagiera approved these changes
Looks good. Left some tiny inline comments to address before merging

2024-10-30 13:44 UTC, kmagiera commented on packages/vscode-extension/src/project/project.ts
> +    this.deviceSession?.sendDeepLink(link);
do we want to await here for consistency?

2024-11-04 08:23 UTC, km1chno commented
I will get back to this once #675 is merged so we can use app level cache for storing recently used deep links

2024-11-04 10:23 UTC, kmagiera commented
There's no reason to wait, this is accepted for a few days already. #675 only changes the storage for build result metadata, we're still storing other settings and data in workspace-specific storage. It doesn't make sense to put URLs storage in that cache leaving other settings in workspace cache as it is conceptually closer to device settings than it is to native builds.

2024-11-04 12:08 UTC, km1chno commented
Ok then I'm merging this one. When the app level cache is created and we feel a need to move app level settings there from workspace state, then we can move cached deep links too.

2024-11-04 12:08 UTC, merged