Draft of MultiRoot Workspace support
software-mansion/radon-ide pull request #663
Opened 2024-10-25 20:34 UTC by filip131311

This PR is a draft because it requires two additional changes that will be coming in separate PR: 

- [ ] multi root build fingerprinting system
- [ ] better way to reload all systems: metro, devtools, device without causing clean rebuild

the aim of this PR is to detect application roots in the workspace and allow for swift change between them.

2025-02-27 10:54 UTC, kmagiera reviewed
Haven't finished revieweing everything but left a few comments already

2025-02-27 10:54 UTC, kmagiera commented on packages/vscode-extension/src/builders/BuildCache.ts
> +  public async storeBuild(buildFingerprint: string, build: BuildResult, platform: DevicePlatform) {
can't we use `buiild.platform` here instead of providing platform as extra argument?

2025-02-27 10:54 UTC, kmagiera commented on packages/vscode-extension/src/builders/customBuild.ts
> +  appRoot: string
nit: in this particular place I'd just call it `cwd` here as the method is pretty abstract, so it doesn't need to have a context that it runs in an app root IMO

2025-02-27 10:54 UTC, kmagiera commented on packages/vscode-extension/src/builders/customBuild.ts
> +export async function runfingerprintCommand(externalCommand: string, env: Env, appRoot: string) {
same here

2025-02-27 10:54 UTC, kmagiera commented on packages/vscode-extension/src/builders/customBuild.ts
> +  appRoot: string,
and here

2025-02-27 10:54 UTC, kmagiera commented on packages/vscode-extension/src/dependency/DependencyManager.ts
> +  public async validateNodeVersion(appRoot: string) {
given DependencyManager already stores appRoot, we shouldn't require it as argument.

2025-02-27 10:54 UTC, kmagiera commented on packages/vscode-extension/src/dependency/DependencyManager.ts
> +  private async getPackageManager(appRoot: string) {
same here, we should use `this.appRootFolder` here, why isn't this consistent?

2025-02-27 11:52 UTC, kmagiera reviewed
Left a couple more inline comments

2025-02-27 11:52 UTC, kmagiera commented on packages/vscode-extension/src/extension.ts
> +    commands.executeCommand("setContext", "RNIDE.extensionIsActive", true);
I don't like that the diagnose method has a side effect like this. We should restructure it and set the context elsewhere. Now running diagnostics will actually fix the editor context ?

2025-02-27 11:52 UTC, kmagiera commented on packages/vscode-extension/src/project/project.ts
> +    this.appRootFolder.setAppRoot(appRoot);
It doesn't seem like having the AppRootFolder class makes sense any longer. We just use it in project and when the app root changes we also only call a code that is defined in the project class.

2025-02-27 11:52 UTC, kmagiera commented on packages/vscode-extension/src/utilities/extensionContext.ts
> +export class AppRootFolder {
I think it'd be cleaner if we get rid of this class and just rely on project controlling changes to appRootFolder value

2025-02-27 11:52 UTC, kmagiera commented on packages/vscode-extension/src/utilities/extensionContext.ts
> +  const searchedFileNames = [
in the previous approach we were also looking for folders that have node_modules with react-native installed. Do we want to change this?

2025-02-27 11:52 UTC, kmagiera commented on packages/vscode-extension/src/utilities/reactNative.ts
> +export function getReactNativeVersion(workspacePath: string) {
maybe we can rename to appRootFolder here?

2025-02-27 13:49 UTC, jwajgelt requested changes

2025-02-27 13:49 UTC, jwajgelt commented on packages/vscode-extension/src/utilities/extensionContext.ts
> +  const searchQueue: [string, number][] | undefined = workspace.workspaceFolders?.map(
I'd rather have this be a record rather than a tuple.
```suggestion
  const searchQueue: {path: string, searchDepth: number}[] | undefined = workspace.workspaceFolders?.map(
```
Right now, you have to read the whole function to figure out what the `string` and `number` here are.

Or even better, make this a named type, since you refer to it in other places.

2025-02-27 13:49 UTC, jwajgelt commented on packages/vscode-extension/src/utilities/extensionContext.ts
> +  }
I think it'd make more sense to instead early return on `workspace.workspaceFolders` being undefined.
```suggestion
  if (workspace.workspaceFolders === undefined) {
    Logger.warn("[FindFiles] Could not determine active workspace");
    return [];
  }

  const searchQueue: [string, number][] = workspace.workspaceFolders.map(
    (workspaceFolder) => {
      return [workspaceFolder.uri.path, 0];
    }
  );
```

2025-02-27 13:49 UTC, jwajgelt commented on packages/vscode-extension/src/utilities/extensionContext.ts
> +  }
Is this something we want to `warn` about? Isn't this expected in a monorepo?

2025-02-27 13:49 UTC, jwajgelt commented on packages/vscode-extension/src/utilities/extensionContext.ts
> +  }
NIT:
I'd move this to a separate function for clarity.

2025-02-27 13:49 UTC, jwajgelt commented on packages/vscode-extension/src/utilities/extensionContext.ts
> +  while (currentDir !== undefined) {
I'd condition the loop on `searchQueue.length` and declare `currentDir` inside its body instead.

2025-02-27 13:49 UTC, jwajgelt commented on packages/vscode-extension/src/utilities/extensionContext.ts
> +  }
I think the body of this `forEach` callback is pretty complex.
I'd rewrite it into two array operations instead, one for checking if you're the candidate and another for selecting children to search. Something along the
```suggestion
    const isCandidate = filesAndDirs.some(dirEntry => {
      return dirEntry.isFile() && searchedFileNames.includes(dirEntry.name);
    });
    
    if (isCandidate) { candidates.push(currentDir[0]) }
    
    const childrenToSearch = filesAndDirs.filter(dirEntry => {
      return !excludedDirectoryPatterns.some((pattern) => pattern.test(dirEntry.name))
    }).map(dirEntry => [currentDir![0] + "/" + dirEntry.name, currentDir![1] + 1]);
    searchQueue.push(...childrenToSearch);

    currentDir = searchQueue.shift();
  }
```

2025-02-27 13:49 UTC, jwajgelt commented on packages/vscode-extension/src/utilities/extensionContext.ts
> +export function findAppRootCandidates(maxSearchDepth: number = 3): string[] {
Nit: this shouldn't be hard to rewrite as a [generator function](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/function*) instead.
This would allow you to only look for the first candidate when activating the extension, and get all of the candidates when generating the list of possible appRoots with the same implementation.

2025-02-27 13:49 UTC, jwajgelt commented on packages/vscode-extension/src/utilities/packageManager.ts
> +  appRoot: string
Maybe `PackageManagerInfo` should hold the `appRoot` instead? Isn't the "Package Manager Info" only relevant in the context of a specific "app root"?

2025-02-27 13:49 UTC, jwajgelt commented on packages/vscode-extension/src/webview/providers/LaunchConfigProvider.tsx
> +    launchConfig.addCustomApplicationRoot(appRoot);
Could we just do:
```suggestion
    launchConfig.addCustomApplicationRoot(appRoot);
```
and rely on the `launchConfig` listener to update it for us?

2025-02-27 17:39 UTC, filip131311 commented on packages/vscode-extension/src/extension.ts
> +    workspace.onDidChangeConfiguration(async (event: ConfigurationChangeEvent) => {
this is a remnant of a previous approach thank you for pointing it out.

2025-02-27 17:49 UTC, filip131311 commented on packages/vscode-extension/src/extension.ts
> +    commands.executeCommand("setContext", "RNIDE.extensionIsActive", true);
It is the old behavior of this command. I agree that it inappropriately named but I would like to constrain the out facing changes to things strictlly related to setting and selecting appRoot as this PR is quite large any way and this seems like a scope creep. I will adres this comment in the fallow up.

2025-02-27 17:54 UTC, filip131311 commented on packages/vscode-extension/src/builders/customBuild.ts
> +  let process = command(externalCommand, { cwd: appRoot, env });
This seems to be a serious problem, that we didn't think about before serious addressing multiRoot configuration, there are more similar problems as well for example right now our configuration is workspace specific for all configuration values so there is now way of setting appRoot specific env. But will adress it in future PRs

2025-02-27 18:03 UTC, filip131311 commented on packages/vscode-extension/src/utilities/extensionContext.ts
> +  }
nice catch i was thinking in therm of the old aproach

2025-02-27 18:04 UTC, filip131311 commented on packages/vscode-extension/src/utilities/extensionContext.ts
> +  }
what do you mean by `this`

2025-02-27 18:16 UTC, filip131311 commented on packages/vscode-extension/src/utilities/extensionContext.ts
> +  }
The point of creating this function was to optimize and iterators in js are not lazy, so this is not a zero-cost abstraction, I agree this would be more readable, but It is a worthy trade of in my opinion

2025-02-27 18:23 UTC, filip131311 commented on packages/vscode-extension/src/utilities/packageManager.ts
> +  appRoot: string
I'm not sure if it ever gonna be useful in the future, but it is not. You theoretically can call `nmp install` in any workspace directory and with the correct setiting all of the will be installed

2025-02-27 18:25 UTC, filip131311 commented on packages/vscode-extension/src/webview/providers/LaunchConfigProvider.tsx
> +    launchConfig.addCustomApplicationRoot(appRoot);
yes, thank you

2025-02-27 18:50 UTC, filip131311 commented on packages/vscode-extension/src/utilities/extensionContext.ts
> +  while (currentDir !== undefined) {
type script is not to happy when you do that I'll leave it as it is

2025-02-28 07:49 UTC, jwajgelt requested changes

2025-02-28 07:49 UTC, jwajgelt commented on packages/vscode-extension/src/project/project.ts
> +          const newAppRoot = this.setupAppRoot();
I think `setupAppRoot` shouldn't return anything -- I think it's a bit confusing when a function is used both for side effects (here, updating the object state) and returning a value.
Just call `setupAppRoot` here and use `this.appRootFolder` instead.

2025-02-28 07:49 UTC, jwajgelt commented on packages/vscode-extension/src/project/project.ts
Right now, the type system allows setting these to undefined, which means that:
1. we have to handle this case everywhere, even though it should be unreachable
2. it won't stop us from accidentally setting these fields to `undefined`.

I think we could work around that by "bundling" these dependencies into a separate object (`ProjectContext`, `ApplicationContext`, I don't know) that:
1. in the constructor, sets up the things that depend on the `appRoot`
2. has a `dispose()` method that cleans them up?
Then we could replace calling `setupAppRoot()` with calling 
```
this.applicationContext.dispose();
this.applicationContext = new ApplicationContext(newAppRoot);
```
and we would have to deal with the `undefined` case here.
The `launchConfig` and `dependencyManager` can be exposed via `get`ters to preserve current API.

2025-02-28 07:49 UTC, jwajgelt commented on packages/vscode-extension/src/utilities/extensionContext.ts
> +type searchItem = { path: string; searchDepth: number };
NIT:
```suggestion
type SearchItem = { path: string; searchDepth: number };
```
Capitalizing types makes the code easier to read at a glance.

2025-02-28 07:49 UTC, jwajgelt commented on packages/vscode-extension/src/utilities/extensionContext.ts
> +    const filesAndDirs = fs.readdirSync(currentDir.path.toString(), { withFileTypes: true });
Is there a good reason for this to be `sync`? Do we want to block the whole extension while we're looking for the appRoot?

2025-02-28 07:53 UTC, jwajgelt commented on packages/vscode-extension/src/utilities/packageManager.ts
> +  appRoot: string
Yes, but `PackageManagerInfo` contains the information on which package manager should be used which, if I understand correctly, depends on the contents of `appRoot`, no? Can't changing the app root could cause the selected package manager to change?

2025-02-28 08:06 UTC, jwajgelt commented on packages/vscode-extension/src/utilities/extensionContext.ts
> +  while (currentDir !== undefined) {
How so?

```tsx
  const searchQueue: searchItem[] = searchDirectories;

  while (searchQueue.length > 0) {
    // NOTE: this is safe because we've just checked `searchQueue` is non-empty
    const { path, searchDepth } = searchQueue.shift()!;
    if (searchDepth > maxDepth) {
      break;
    }

    const filesAndDirs = fs.readdirSync(path.toString(), { withFileTypes: true });

    let matched = false;

    filesAndDirs.forEach((dirEntry) => {
      if (dirEntry.isFile()) {
        if (!matched && searchedFileNames.includes(dirEntry.name)) {
          results.push(path);
          matched = true;
        }
        return;
      }

      if (excludedDirectoryPatterns.some((pattern) => pattern.test(dirEntry.name))) {
        return;
      }

      searchQueue.push({
        path: path + "/" + dirEntry.name,
        searchDepth: searchDepth + 1,
      });
    });
  }

  return results;
```

this typechecks correctly for me.

2025-02-28 08:07 UTC, jwajgelt commented on packages/vscode-extension/src/utilities/extensionContext.ts
> +  while (currentDir !== undefined) {
And if you don't trust the non-null assertion next to shift, you can always check for `undefined` and `break` explicitely.

2025-02-28 08:16 UTC, jwajgelt commented on packages/vscode-extension/src/utilities/extensionContext.ts
> +          commands.executeCommand("workbench.action.debug.configure");
Is this the correct action for this? For me it opens the command palette, while I'd expect it to open _our_ launch configuration menu (where I can actually select the app root).

2025-02-28 08:20 UTC, jwajgelt commented on packages/vscode-extension/src/project/project.ts
Honestly, I feel like the "`Project`" should just take the `appRoot` in the constructor, and be created again whenever the app root changes, but I feel like that would break some other assumptions elsewhere at this point.

2025-02-28 08:51 UTC, filip131311 commented on packages/vscode-extension/src/project/project.ts
> Honestly, I feel like the "Project" should just take the appRoot in the constructor, and be created again whenever the app root changes, but I feel like that would break some other assumptions elsewhere at this point.

We were discussing that option but there is just too much te project class do, includeing the device management which should not be restarted on app root change, we will work towards untangling those functionalities in the future and then It will be posible

2025-02-28 09:41 UTC, filip131311 commented on packages/vscode-extension/src/utilities/extensionContext.ts
> +          commands.executeCommand("workbench.action.debug.configure");
I don't know why it opens a command palet for you, It works for me and opens a correct configuration file, In the future i would love to migrete to opening our configuration panel but i feel like it is not stable enough yet.

2025-02-28 09:42 UTC, filip131311 commented on packages/vscode-extension/src/utilities/extensionContext.ts
> +          commands.executeCommand("workbench.action.debug.configure");
could you run this comand from command palet and see what happens? do you use cursor or vs code?

2025-02-28 09:44 UTC, filip131311 commented on packages/vscode-extension/src/utilities/extensionContext.ts
> +    const filesAndDirs = fs.readdirSync(currentDir.path.toString(), { withFileTypes: true });
making it async would require as to chege how we build large part of the extension and refactor multiple clases to use builder pattern instead of constructor, we might do it in the future if it turns out to be benefitial but it is a large change for a small improvement

2025-02-28 09:46 UTC, filip131311 commented on packages/vscode-extension/src/utilities/extensionContext.ts
> +type searchItem = { path: string; searchDepth: number };
good catch

2025-02-28 09:57 UTC, filip131311 commented on packages/vscode-extension/src/utilities/packageManager.ts
> +  appRoot: string
It sometimes could, but it is unlikely, but at the end of the day the important question is not if those values are sometimes related but if there might be the situation ever of changing only one of them and as I have written above there might be

2025-02-28 09:58 UTC, filip131311 commented on packages/vscode-extension/src/project/project.ts
overall the sugestion to move those objects to the separet class was exactly what I was missing thank you

2025-02-28 10:29 UTC, jwajgelt commented on packages/vscode-extension/src/utilities/extensionContext.ts
> +          commands.executeCommand("workbench.action.debug.configure");
VSCode.
It's probably because I don't have the file in that project.

2025-02-28 10:42 UTC, jwajgelt commented on packages/vscode-extension/src/utilities/packageManager.ts
> +  appRoot: string
But this is what I mean -- if you change the `appRoot` you probably want to recreate the `PackageManagerInfo`, right?
The way it's written right now, you supply them separately, so you may provide the "wrong" `PackageManagerInfo`, i.e. one unrelated to the passed `appRoot`.

2025-02-28 11:23 UTC, jwajgelt requested changes

2025-02-28 11:23 UTC, jwajgelt commented on packages/vscode-extension/src/project/applicationContext.ts
> +  }
We have a helper `disposeAll` function in utils, use that instead.

2025-02-28 11:23 UTC, jwajgelt commented on packages/vscode-extension/src/utilities/extensionContext.ts
> +          searchDepth: currentDir!.searchDepth + 1,
```suggestion
          path: currentDir.path + "/" + dir.name,
          searchDepth: currentDir.searchDepth + 1,
```

2025-02-28 11:23 UTC, jwajgelt commented on packages/vscode-extension/src/project/applicationContext.ts
Shouldn't the file name be capitalized?

2025-02-28 11:23 UTC, jwajgelt commented on packages/vscode-extension/src/project/applicationContext.ts
> +    }
NIT: I think I'd prefer if the `appRootFolder` was passed as an argument to the constructor to remove as much "logic" from it, but that's just my opinion.

2025-02-28 11:45 UTC, jwajgelt approved these changes

2025-02-28 12:44 UTC, merged