Add Linux support for VSCode extension (#688)
software-mansion/radon-ide pull request #829
Opened 2024-12-04 21:31 UTC by tobisamuel

This PR adds Linux support to the VSCode extension, implementing platform-specific paths and configurations. The changes follow patterns established in PR #462 (Windows support) and make the extension functional on Linux systems.

- Add Linux as a supported platform in Platform module
- Implement Linux paths for Android SDK and tooling
- Add Linux-specific configurations for file system and processes
- Update UI components to handle Linux keyboard shortcuts

Fixes #688

2024-12-05 10:35 UTC, maciekstosio reviewed
Thank you for contributing! One initial nitpick. We need to test it, but it looks good at first sight.

2024-12-05 10:35 UTC, maciekstosio commented on packages/vscode-extension/src/extension.ts
> +    window.showErrorMessage("Radon IDE works only on macOS and Windows and Linux.", "Dismiss");
```suggestion
    window.showErrorMessage("Radon IDE works only on macOS, Windows and Linux.", "Dismiss");
```
Although, I wonder if we still need this error.

2024-12-05 11:39 UTC, kmagiera requested changes
Thanks @tobisamuel for working on this.

The code looks good, however, I'd like if you could update the PR description with test plan. Specifically we want to know what and how you tested things. This way in the future we could tell at which point things broke or whether things just weren't tested. Would be the best if you could upload some screen recording showcasing the tool in action on Linux too.

Thank you!

2024-12-06 11:51 UTC, tobisamuel commented
Hi @kmagiera,

Thanks for the feedback! I have updated the PR description to include a detailed test plan, outlining what and how I tested the changes on my Linux system. Additionally, I have attached a screen recording showcasing the extension in action on Linux.

Please let me know if there's anything else you'd like me to address!

2024-12-06 11:52 UTC, kmagiera approved these changes
This is perfect now, thank you!

2024-12-06 11:58 UTC, kmagiera commented
@tobisamuel – looks like lint is failing due to code formatting issue. You should be able to resolve this by running `npm run format` in the main project directory

2024-12-07 12:09 UTC, tobisamuel commented
Fixed the formatting issues @kmagiera. The lint checks should now pass.

2024-12-09 10:15 UTC, merged