feat: preview background
software-mansion/radon-ide pull request #874
Opened 2024-12-21 15:39 UTC by kewinzaq1

This merge request adds support for vscode themes

2024-12-23 09:14 UTC, filip131311 requested changes
Hello, thank you for your time. 
In general I really like the changes unfortunately there are some parts of the application that lose on readability after the changes, for example lunchConfiguration:
<img width="459" alt="Screenshot 2024-12-23 at 10 08 55" src="https://github.com/user-attachments/assets/b42fd9a6-3df9-4494-b672-eb559a6b28a9" />
 
Vscode has styled inputs: 
<img width="611" alt="Screenshot 2024-12-23 at 10 11 28" src="https://github.com/user-attachments/assets/8bfd4e3e-e9dd-4852-b6a5-3bc8027c5374" />
<img width="589" alt="Screenshot 2024-12-23 at 10 11 35" src="https://github.com/user-attachments/assets/fce33bb5-634a-4705-ba61-26fc915ad86e" />

so i believe you can find the styles for them 

I also left one inline question 

Thank u again and merry Christmas

2024-12-23 16:06 UTC, kewinzaq1 commented
> Hello, thank you for your time. In general I really like the changes unfortunately there are some parts of the application that lose on readability after the changes, for example lunchConfiguration: <img alt="Screenshot 2024-12-23 at 10 08 55" width="459" src="https://private-user-images.githubusercontent.com/159789821/398113734-b42fd9a6-3df9-4494-b672-eb559a6b28a9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ5NzAyMjEsIm5iZiI6MTczNDk2OTkyMSwicGF0aCI6Ii8xNTk3ODk4MjEvMzk4MTEzNzM0LWI0MmZkOWE2LTNkZjktNDQ5NC1iNjcyLWViNTU5YTZiMjhhOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyM1QxNjA1MjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01OWZlZDA4YWEyMjYwYjg4YmYzOWRmOTlhMDJiNGMzMzZlZDVkODU0MjQ4ZDU1MzA5ZjNkNzIwYWU3NDhkMjA1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.9n5dEGWE3qGJfB5GxIwlogwkPoNWeJ-rNQgcPnMxveQ">
> 
> Vscode has styled inputs: <img alt="Screenshot 2024-12-23 at 10 11 28" width="611" src="https://private-user-images.githubusercontent.com/159789821/398114002-8bfd4e3e-e9dd-4852-b6a5-3bc8027c5374.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ5NzAyMjEsIm5iZiI6MTczNDk2OTkyMSwicGF0aCI6Ii8xNTk3ODk4MjEvMzk4MTE0MDAyLThiZmQ0ZTNlLWU5ZGQtNDg1Mi1iNmE1LTNiYzgwMjdjNTM3NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyM1QxNjA1MjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01ZDU2MTM1NjZjOTUxYWUxOTBjOWIyZTliZDJhNjAwMTc5NGQyYzI5NzhhZjA4M2ZjODU4MWRjZjg0NTIyYTkwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.fMK9RsZUFq2vn900Bt7qGd6Rxa-wIYIepq_Dx7m8LGk"> <img alt="Screenshot 2024-12-23 at 10 11 35" width="589" src="https://private-user-images.githubusercontent.com/159789821/398114003-fce33bb5-634a-4705-ba61-26fc915ad86e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ5NzAyMjEsIm5iZiI6MTczNDk2OTkyMSwicGF0aCI6Ii8xNTk3ODk4MjEvMzk4MTE0MDAzLWZjZTMzYmI1LTYzNGEtNDcwNS1iYTYxLTI2ZmM5MTVhZDg2ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyM1QxNjA1MjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05ZDg1ZmZhYmNlODRjNTdiZmVkZTUxZDVjZGQwOTQ3YzJmYTA5ZjE1NTEyMDRjMTRlMDJhZjNkODhlYTEyMDkxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9._9puzzSlXibkHKBwVF4VuwKRR1K0YiYYQ1zMWiwlzsI">
> 
> so i believe you can find the styles for them
> 
> I also left one inline question
> 
> Thank u again and merry Christmas

Thanks for the review merry Christmas 🎄

2025-01-08 09:35 UTC, kmagiera commented
I'd also be in favor of supporting themes properly. The reason we decided to shift away from this approach initially was that it was difficult to control some of the theme parameters under different vscode settings. This resulted in a number of elements being difficult to use as they'd blend inproperly into elements in the background for example. 

One way this can be solved is be giving an option whether the IDE should use the editor theme or the built-in one. I wonder how difficult would it be to incorporate that while still relying mostly on css variables.

2025-01-09 16:52 UTC, kewinzaq1 commented
> One way this can be solved is be giving an option whether the IDE should use the editor theme or the built-in one. I wonder how difficult would it be to incorporate that while still relying mostly on css variables.

@kmagiera I think that it should go quite smoothly. I'll return with an example of it. One thing that is striking in this approach is that it would hurt UX a bit, forcing users to manually switch to the default theme. You know, I mean the experience that something does not look well and then someone would report this because overlooked this option in workspace config or so. But maybe I exaggerate.

2025-01-09 17:11 UTC, kmagiera commented
I agree such a setting would be difficult to discover. Perhaps we should default to the editor theme and only expect the setting to be used as a fallback when the UI doesn't look good in certain theme

2025-01-14 16:25 UTC, kewinzaq1 commented
> This looks good. Thank you. Anything you're planning to change as this PR is still marked as draft? We won't be merging it for the upcoming release (this week), but may want to include it for the following one

@kmagiera great, I'm not planning to change anything for now, so I think we can remove the draft label

2025-01-20 09:25 UTC, filip131311 approved these changes
This is awesome, thank you so much for your contribution! 

We will include this in next release.

2025-01-20 09:25 UTC, merged