Refactor screen recording and add key bindings
software-mansion/radon-ide pull request #875
Opened 2024-12-23 12:43 UTC by filip131311

This PR aims to add keybindings for capturing replays, starting an capturing the recording. 
To achieve that we need to move the logic for starting and ending recording from webview to the extension code. 

the proposed keybindings are:
- capture replay: shift+cmd+R
- start recording: shift+cmd+E
- capture recording: shift+cmd+T

### How Has This Been Tested: 

- Run extension and check if commands and previously existing buttons work as expected 
- change `MAX_RECORDING_TIME_SEC` to 10 and check if the logic for closing stoping works 

https://github.com/user-attachments/assets/9457f827-b711-4c44-9fd1-d256b8f268bb

2025-01-07 11:57 UTC, maciekstosio requested changes

2025-01-07 11:57 UTC, maciekstosio commented on packages/vscode-extension/package.json
> +        "title": "Capture Recording",
I wonder if End recording wouldn't be more readable. Or maybe just one command for toggle recording?

2025-01-07 11:57 UTC, maciekstosio commented on packages/vscode-extension/package.json
> +        "command": "RNIDE.captureReplay",
I don't like those shortcuts. Usually, the keys used are somehow related to what they do, and I think shift is used for something special for given base shortcut `cmd+z` -> undo, `cmd+shift+z` -> redo. All that we use doesn't seem to have any meaning, or I don't see one.
I was thinking about something like:

ctrl + b/a -> biometric/authorization
ctrl + shift + b/a -> perform failed biometric/authorization
ctrl + r -> toggle recording 
ctrl + shift + r -> show replay 
ctrl + s -> screen shot 

wdyt?

2025-01-07 11:57 UTC, maciekstosio commented on packages/vscode-extension/src/common/Project.ts
> +  captureAndStopRecording(): void;
just endRecording?

2025-01-07 11:57 UTC, maciekstosio commented on packages/vscode-extension/src/devices/preview.ts
> +  private saveMultimediaWithID(type: "video" | "screenshot", id: string): Promise<MultimediaData> {
Could we have some enum for `type`?
This part:
```
 public captureReplay() {


     return this.saveMultimediaWithID("video", "replay");
   }

   public captureScreenShot() {
     return this.saveMultimediaWithID("screenshot", "screenshot");
   }
```

would become cleaner imo.

2025-01-07 11:57 UTC, maciekstosio commented on packages/vscode-extension/src/project/project.ts
> +    this.recordingInterval = setInterval(() => {
Why not just `setTimeout`?

2025-01-07 11:57 UTC, maciekstosio commented on packages/vscode-extension/src/project/project.ts
> +    this.eventEmitter.emit("isRecordingChanged", true);
This event name is a bit confusing for me, maybe we can come up with something better?

2025-01-07 11:57 UTC, maciekstosio commented on packages/vscode-extension/src/project/project.ts
> +    this.eventEmitter.emit("isRecordingChanged", true);
isRecording? RECORDING_STATE_CHAGNED?

2025-01-08 12:33 UTC, filip131311 commented on packages/vscode-extension/package.json
> +        "command": "RNIDE.captureReplay",
unfortunately api you proposed clashes with existing keybindings (file save/ resent workspaces) 

I refactored my api to look like this 
cmd+shift+r capture replay
cmd+shift+e toggle recording 
cmd+shift+a capture screenshot

2025-01-09 08:47 UTC, maciekstosio approved these changes

2025-01-09 08:53 UTC, merged