Support for launching expo dev plugin tools in separate panels within VSCode
software-mansion/radon-ide pull request #878
Opened 2024-12-31 12:08 UTC by kmagiera

This PR adds support for redux and react query dev tools expo plugins and makes their UI display as separate panel in VSCode.

Apart from the support for the listed plugins, this change builds an infrastructure for supporting more expo dev plugins and other types of plugins in the future.

Key changes that the PR introduces:
1. We restructure the logic for creating and accessing some core extension components like Project, DeviceManager, etc. Before they were instantiated in webview panel or tabview controller. In this PR we are introducing a new top level class IDE that controls the lifecycle of all the listed core components and hooks them up properly as some instances require other instances to exists. As a side effect of this change, we no longer re-create project when switching between UI location for the Radon IDE panel (between tab and side-panel)
2. We are expanding panels configuration in package.json. Apparently there's no way to define panels dynamically and we need one panel for every dev tool such that they can be run side-by-side when necessary. To avoid having too many panels, every panel is hidden behind its own context variable that we can dynamically set when we detect the user requested to open this panel
3. We introduce a change to babel transformer that allows us to capture the use of expo-dev-plugins we currently support. This way we can detect which plugins the user has installed and only show relevant tools for the user to open.
4. For the above to work correctly, we are adding a new type of event that is passed via the devtools channel (same that we use for events such as "app ready"). We use this event to notify about the plugins that the app uses.
5. We're adding a UI component to the top menu bar with a "tools" dropdown. The dropdown displays the list of available tools and a checkbox next to every tool allowing the user to enable each tool separately. When tools is enabled, the new panel displaying the tool UI will launch.
6. Finally, we're implementing a new "ToolPlugin" interface and its implementation that coordinates all the expo-dev-plugin specific needs. The interface allows for tools to be listed as available and implements a persistent storage for saving which tools are enabled. The expo-dev-plugin implementation of the tool manages the registration of webview panels, listening to events about the plugins being used by the app, and controls the context variables that shows/hide the panel.

As a follow up to this change, we will be adding a docs update that explains how tools can be used. Currently, we only support epxo-dev-plugin tools, so for the whole setup to work corrently the user needs to use Expo and have the specific tools configured according to the documentation here: https://github.com/expo/dev-plugins

### How Has This Been Tested: 
1. I used a sample Expo project and added redux and react query dev tools following the docs here: https://github.com/expo/dev-plugins
2. I tested enabling/disabling each plugin separately. When plugin is enabled we expect the panel to open immediately.
3. I tested resetting metro cache which forces metro to reset at which point it stars at a new port. This is important as the plugin UI is hosted via metro. In this scenario is it expected for the panel to close while the app is reloading.
4. I tested switching between tab and side-panel views to make sure the core class insistence changes didn't break anything.

2025-01-10 13:23 UTC, filip131311 reviewed
I left an inline comment

2025-01-13 14:34 UTC, filip131311 requested changes
I left some inline comments

2025-01-13 14:34 UTC, filip131311 commented on packages/vscode-extension/src/plugins/expo-dev-plugins/ExpoDevPluginWebviewProvider.ts
> +      <body style="height: 100%;">
```suggestion
      <body style="height: 100%; overflow:hidden">
```

this will remove the scroll bar next to the panel.

2025-01-13 14:34 UTC, filip131311 commented on packages/vscode-extension/src/project/project.ts
> +      oldToolsManager.dispose();
I'm not sure if removing the old tools manager and creating a new one is what we should do here: 
this action causes the plug in panel to disappear completely for the time of the restart which if the panel was open looks bad for the user, I think we should pass an information to the tools manager about restart and while plug in is not available display some kind of loading in the panel. We should also add a functionality to the tools manager that allows us to update any information it needs after restart (like metro port)

2025-01-13 14:34 UTC, filip131311 commented on packages/vscode-extension/package.json
> +          "when": "RNIDE.Tool.ExpoDevPlugin.ReactQuery.available"
```suggestion
          "when": "RNIDE.Tool.ExpoDevPlugin.ReactQuery.available && RNIDE.panelIsOpen"
```

I think we should hide plug in panels when no app is running

2025-01-13 17:58 UTC, maciekstosio approved these changes
Looks good

2025-01-14 09:54 UTC, kmagiera commented on packages/vscode-extension/src/project/project.ts
> +      oldToolsManager.dispose();
yes, I know this isn't ideal but this is apparently the best we can do without complicating this immensely. The panel will end up loosing its state which is outside of our control here. This is because after restart we will need to connect to the new instance of metro. Ultimately, I'd rather keep it this way for now.

Ultimately, we can add more integrated tools that could work without installing additional plugin modules which I think is going to be more convenient. In that case we will also have better flexibility as to how restarts can be controlled and when to retain the tool state.

2025-01-14 10:06 UTC, merged